version: '3'
services:

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    # volumes:
    #   - "./mongo-db:/data/db"

  recovery-toolkit:
    build: .
    ports:
      - "5000:5000" # manual HTTP calls
    depends_on:
      - mongodb
    links:
      - mongodb